[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tos/src/linker.ld", 
    "-Cforce-frame-pointers=yes"
]

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tos/src/linker.ld",
    "-Cforce-frame-pointers=yes", 
    "-Ctarget-feature=-lsx,-lasx",
]

[net]
git-fetch-with-cli = true